/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 36
#line 1 "/Users/rasmus/Development/C/uri/src/uri.leg"

#include "uri/element.h"
#include <stdio.h>

#define YYSTYPE element *
#ifdef __DEBUG__
#define YY_DEBUG 1
#endif

#define YY_INPUT(buf, result, max_size)                                        \
  {                                                                            \
    int yyc;                                                                   \
    if (charbuf && *charbuf != '\0') {                                         \
      yyc = *charbuf++;                                                        \
    } else {                                                                   \
      yyc = EOF;                                                               \
    }                                                                          \
    result = (EOF == yyc) ? 0 : (*(buf) = yyc, 1);                             \
  }

#define YY_RULE(T) T


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_gendelims(yycontext *yy); /* 36 */
YY_RULE(int) yy_reserved(yycontext *yy); /* 35 */
YY_RULE(int) yy_decoctet(yycontext *yy); /* 34 */
YY_RULE(int) yy_ls32(yycontext *yy); /* 33 */
YY_RULE(int) yy_h16(yycontext *yy); /* 32 */
YY_RULE(int) yy_hexdigit(yycontext *yy); /* 31 */
YY_RULE(int) yy_IPvFuture(yycontext *yy); /* 30 */
YY_RULE(int) yy_IPv6address(yycontext *yy); /* 29 */
YY_RULE(int) yy_regname(yycontext *yy); /* 28 */
YY_RULE(int) yy_IPv4address(yycontext *yy); /* 27 */
YY_RULE(int) yy_IPliteral(yycontext *yy); /* 26 */
YY_RULE(int) yy_port(yycontext *yy); /* 25 */
YY_RULE(int) yy_host(yycontext *yy); /* 24 */
YY_RULE(int) yy_userinfo(yycontext *yy); /* 23 */
YY_RULE(int) yy_subdelims(yycontext *yy); /* 22 */
YY_RULE(int) yy_pctencoded(yycontext *yy); /* 21 */
YY_RULE(int) yy_unreserved(yycontext *yy); /* 20 */
YY_RULE(int) yy_pchar(yycontext *yy); /* 19 */
YY_RULE(int) yy_segmentnznc(yycontext *yy); /* 18 */
YY_RULE(int) yy_segmentnz(yycontext *yy); /* 17 */
YY_RULE(int) yy_segment(yycontext *yy); /* 16 */
YY_RULE(int) yy_pathnoscheme(yycontext *yy); /* 15 */
YY_RULE(int) yy_path(yycontext *yy); /* 14 */
YY_RULE(int) yy_pathempty(yycontext *yy); /* 13 */
YY_RULE(int) yy_pathrootless(yycontext *yy); /* 12 */
YY_RULE(int) yy_pathabsolute(yycontext *yy); /* 11 */
YY_RULE(int) yy_pathabempty(yycontext *yy); /* 10 */
YY_RULE(int) yy_authority(yycontext *yy); /* 9 */
YY_RULE(int) yy_digit(yycontext *yy); /* 8 */
YY_RULE(int) yy_alpha(yycontext *yy); /* 7 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 6 */
YY_RULE(int) yy_fragment(yycontext *yy); /* 5 */
YY_RULE(int) yy_query(yycontext *yy); /* 4 */
YY_RULE(int) yy_hierpart(yycontext *yy); /* 3 */
YY_RULE(int) yy_Scheme(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_hexdigit(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_hexdigit\n"));
  {
#line 105
  2;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_fragment(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_fragment\n"));
  {
#line 90
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_query(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_query\n"));
  {
#line 88
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_h16(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_h16\n"));
  {
#line 78
  4;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_IPv6address\n"));
  {
#line 70
  2;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_IPv6address\n"));
  {
#line 69
  3;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_IPv6address\n"));
  {
#line 68
  4;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_IPv6address\n"));
  {
#line 67
  5;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IPv6address\n"));
  {
#line 66
  6;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_port\n"));
  {
#line 59
   __ = mk_integer(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_host(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_host\n"));
  {
#line 57
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_userinfo(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_userinfo\n"));
  {
#line 55
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_authority(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define h yy->__val[-2]
#define u yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_authority\n"));
  {
#line 53
   __ = mk_authority(u,h,p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef h
#undef u
}
YY_ACTION(void) yy_2_hierpart(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_hierpart\n"));
  {
#line 33
   __ = mk_hirhierarchical_part(mk_str(yytext), 0); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_hierpart(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_hierpart\n"));
  {
#line 32
   __ = mk_hirhierarchical_part(mk_str(yytext), a); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_Scheme(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Scheme\n"));
  {
#line 30
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_start(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define q yy->__val[-2]
#define h yy->__val[-3]
#define s yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
  {
#line 26
  
  parse_result = mk_uri(s, h, q, f);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef q
#undef h
#undef s
}

YY_RULE(int) yy_gendelims(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "gendelims"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '/')) goto l4;  goto l2;
  l4:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '?')) goto l5;  goto l2;
  l5:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '#')) goto l6;  goto l2;
  l6:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '[')) goto l7;  goto l2;
  l7:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, ']')) goto l8;  goto l2;
  l8:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '@')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "gendelims", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "gendelims", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_reserved(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "reserved"));
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;  if (!yy_gendelims(yy)) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;  if (!yy_subdelims(yy)) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "reserved", yy->__buf+yy->__pos));
  return 1;
  l9:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "reserved", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_decoctet(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "decoctet"));
  l13:;	
  {  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;  if (!yy_digit(yy)) goto l14;  goto l13;
  l14:;	  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "decoctet", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_ls32(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ls32"));
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yy_h16(yy)) goto l17;  if (!yymatchChar(yy, ':')) goto l17;  if (!yy_h16(yy)) goto l17;  goto l16;
  l17:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;  if (!yy_IPv4address(yy)) goto l15;
  }
  l16:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ls32", yy->__buf+yy->__pos));
  return 1;
  l15:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ls32", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_h16(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "h16"));  if (!yy_hexdigit(yy)) goto l18;  yyDo(yy, yy_1_h16, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "h16", yy->__buf+yy->__pos));
  return 1;
  l18:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "h16", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hexdigit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hexdigit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l19;  yyDo(yy, yy_1_hexdigit, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPvFuture(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPvFuture"));  if (!yymatchChar(yy, 'v')) goto l20;  if (!yy_hexdigit(yy)) goto l20;  if (!yymatchChar(yy, '.')) goto l20;
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l24;  goto l23;
  l24:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yy_subdelims(yy)) goto l25;  goto l23;
  l25:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;  if (!yymatchChar(yy, ':')) goto l21;
  }
  l23:;	  goto l22;
  l21:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;
  }
  l22:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IPvFuture", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPvFuture", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPv6address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPv6address"));
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yy_h16(yy)) goto l28;  if (!yymatchChar(yy, ':')) goto l28;  yyDo(yy, yy_1_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l28;  goto l27;
  l28:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchString(yy, "::")) goto l29;  if (!yy_h16(yy)) goto l29;  if (!yymatchChar(yy, ':')) goto l29;  yyDo(yy, yy_2_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l29;  goto l27;
  l29:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\000\102\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l30;  if (!yymatchString(yy, "::")) goto l30;  if (!yy_h16(yy)) goto l30;  if (!yymatchChar(yy, ':')) goto l30;  yyDo(yy, yy_3_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l30;  goto l27;
  l30:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\102\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l31;  if (!yymatchString(yy, "::")) goto l31;  if (!yy_h16(yy)) goto l31;  if (!yymatchChar(yy, ':')) goto l31;  yyDo(yy, yy_4_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l31;  goto l27;
  l31:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\106\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;  if (!yymatchString(yy, "::")) goto l32;  if (!yy_h16(yy)) goto l32;  if (!yymatchChar(yy, ':')) goto l32;  yyDo(yy, yy_5_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l32;  goto l27;
  l32:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\112\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l33;  if (!yymatchString(yy, "::")) goto l33;  if (!yy_h16(yy)) goto l33;  if (!yymatchChar(yy, ':')) goto l33;  if (!yy_ls32(yy)) goto l33;  goto l27;
  l33:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\122\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l34;  if (!yymatchString(yy, "::")) goto l34;  if (!yy_ls32(yy)) goto l34;  goto l27;
  l34:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\142\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l35;  if (!yymatchString(yy, "::")) goto l35;  if (!yy_h16(yy)) goto l35;  goto l27;
  l35:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\102\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;  if (!yymatchString(yy, "::")) goto l26;
  }
  l27:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IPv6address", yy->__buf+yy->__pos));
  return 1;
  l26:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPv6address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_regname(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "regname"));
  {  int yypos39= yy->__pos, yythunkpos39= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l40;  goto l39;
  l40:;	  yy->__pos= yypos39; yy->__thunkpos= yythunkpos39;  if (!yy_pctencoded(yy)) goto l41;  goto l39;
  l41:;	  yy->__pos= yypos39; yy->__thunkpos= yythunkpos39;  if (!yy_subdelims(yy)) goto l36;
  }
  l39:;	
  l37:;	
  {  int yypos38= yy->__pos, yythunkpos38= yy->__thunkpos;
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yy_pctencoded(yy)) goto l44;  goto l42;
  l44:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yy_subdelims(yy)) goto l38;
  }
  l42:;	  goto l37;
  l38:;	  yy->__pos= yypos38; yy->__thunkpos= yythunkpos38;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "regname", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "regname", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPv4address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPv4address"));  if (!yy_decoctet(yy)) goto l45;  if (!yymatchChar(yy, '.')) goto l45;  if (!yy_decoctet(yy)) goto l45;  if (!yymatchChar(yy, '.')) goto l45;  if (!yy_decoctet(yy)) goto l45;  if (!yymatchChar(yy, '.')) goto l45;  if (!yy_decoctet(yy)) goto l45;
  yyprintf((stderr, "  ok   %s @ %s\n", "IPv4address", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPv4address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPliteral(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPliteral"));  if (!yymatchChar(yy, '[')) goto l46;
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_IPv6address(yy)) goto l48;  goto l47;
  l48:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yy_IPvFuture(yy)) goto l46;
  }
  l47:;	  if (!yymatchChar(yy, ']')) goto l46;
  yyprintf((stderr, "  ok   %s @ %s\n", "IPliteral", yy->__buf+yy->__pos));
  return 1;
  l46:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPliteral", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "port"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l49;
#undef yytext
#undef yyleng
  }  if (!yy_digit(yy)) goto l49;
  l50:;	
  {  int yypos51= yy->__pos, yythunkpos51= yy->__thunkpos;  if (!yy_digit(yy)) goto l51;  goto l50;
  l51:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l49;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 1;
  l49:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_host(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "host"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l52;
#undef yytext
#undef yyleng
  }
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yy_IPliteral(yy)) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yy_IPv4address(yy)) goto l55;  goto l53;
  l55:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yy_regname(yy)) goto l52;
  }
  l53:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l52;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_host, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "host", yy->__buf+yy->__pos));
  return 1;
  l52:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "host", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_userinfo(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "userinfo"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l56;
#undef yytext
#undef yyleng
  }
  {  int yypos59= yy->__pos, yythunkpos59= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l60;  goto l59;
  l60:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yy_pctencoded(yy)) goto l61;  goto l59;
  l61:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yy_subdelims(yy)) goto l62;  goto l59;
  l62:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;  if (!yymatchChar(yy, ':')) goto l56;
  }
  l59:;	
  l57:;	
  {  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l64;  goto l63;
  l64:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yy_pctencoded(yy)) goto l65;  goto l63;
  l65:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yy_subdelims(yy)) goto l66;  goto l63;
  l66:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchChar(yy, ':')) goto l58;
  }
  l63:;	  goto l57;
  l58:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l56;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_userinfo, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "userinfo", yy->__buf+yy->__pos));
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "userinfo", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_subdelims(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "subdelims"));
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yymatchChar(yy, '!')) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '$')) goto l70;  goto l68;
  l70:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '&')) goto l71;  goto l68;
  l71:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '\'')) goto l72;  goto l68;
  l72:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '(')) goto l73;  goto l68;
  l73:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, ')')) goto l74;  goto l68;
  l74:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '*')) goto l75;  goto l68;
  l75:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '+')) goto l76;  goto l68;
  l76:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, ',')) goto l77;  goto l68;
  l77:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, ';')) goto l78;  goto l68;
  l78:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, '=')) goto l67;
  }
  l68:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "subdelims", yy->__buf+yy->__pos));
  return 1;
  l67:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "subdelims", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pctencoded(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pctencoded"));  if (!yymatchChar(yy, '%')) goto l79;  if (!yy_hexdigit(yy)) goto l79;
  yyprintf((stderr, "  ok   %s @ %s\n", "pctencoded", yy->__buf+yy->__pos));
  return 1;
  l79:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pctencoded", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_unreserved(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "unreserved"));
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;  if (!yy_alpha(yy)) goto l82;  goto l81;
  l82:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yy_digit(yy)) goto l83;  goto l81;
  l83:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yymatchChar(yy, '-')) goto l84;  goto l81;
  l84:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yymatchChar(yy, '.')) goto l85;  goto l81;
  l85:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yymatchChar(yy, '_')) goto l86;  goto l81;
  l86:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yymatchChar(yy, '~')) goto l80;
  }
  l81:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "unreserved", yy->__buf+yy->__pos));
  return 1;
  l80:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unreserved", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pchar(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pchar"));
  {  int yypos88= yy->__pos, yythunkpos88= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l89;  goto l88;
  l89:;	  yy->__pos= yypos88; yy->__thunkpos= yythunkpos88;  if (!yy_pctencoded(yy)) goto l90;  goto l88;
  l90:;	  yy->__pos= yypos88; yy->__thunkpos= yythunkpos88;  if (!yy_subdelims(yy)) goto l91;  goto l88;
  l91:;	  yy->__pos= yypos88; yy->__thunkpos= yythunkpos88;  if (!yymatchChar(yy, ':')) goto l92;  goto l88;
  l92:;	  yy->__pos= yypos88; yy->__thunkpos= yythunkpos88;  if (!yymatchChar(yy, '@')) goto l87;
  }
  l88:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pchar", yy->__buf+yy->__pos));
  return 1;
  l87:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pchar", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segmentnznc(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "segmentnznc"));
  {  int yypos96= yy->__pos, yythunkpos96= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l97;  goto l96;
  l97:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yy_pctencoded(yy)) goto l98;  goto l96;
  l98:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yy_subdelims(yy)) goto l99;  goto l96;
  l99:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yymatchChar(yy, '@')) goto l93;
  }
  l96:;	
  l94:;	
  {  int yypos95= yy->__pos, yythunkpos95= yy->__thunkpos;
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l101;  goto l100;
  l101:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yy_pctencoded(yy)) goto l102;  goto l100;
  l102:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yy_subdelims(yy)) goto l103;  goto l100;
  l103:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;  if (!yymatchChar(yy, '@')) goto l95;
  }
  l100:;	  goto l94;
  l95:;	  yy->__pos= yypos95; yy->__thunkpos= yythunkpos95;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segmentnznc", yy->__buf+yy->__pos));
  return 1;
  l93:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "segmentnznc", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segmentnz(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "segmentnz"));  if (!yy_pchar(yy)) goto l104;
  l105:;	
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy_pchar(yy)) goto l106;  goto l105;
  l106:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segmentnz", yy->__buf+yy->__pos));
  return 1;
  l104:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "segmentnz", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segment(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "segment"));
  l108:;	
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yy_pchar(yy)) goto l109;  goto l108;
  l109:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segment", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_pathnoscheme(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathnoscheme"));  if (!yy_segmentnznc(yy)) goto l110;
  l111:;	
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l112;  if (!yy_segment(yy)) goto l112;  goto l111;
  l112:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathnoscheme", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathnoscheme", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_path(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "path"));
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yy_pathabempty(yy)) goto l115;  goto l114;
  l115:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;  if (!yy_pathabsolute(yy)) goto l116;  goto l114;
  l116:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;  if (!yy_pathnoscheme(yy)) goto l117;  goto l114;
  l117:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;  if (!yy_pathrootless(yy)) goto l118;  goto l114;
  l118:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;  if (!yy_pathempty(yy)) goto l113;
  }
  l114:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "path", yy->__buf+yy->__pos));
  return 1;
  l113:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "path", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathempty(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "pathempty"));
  {  int yypos120= yy->__pos, yythunkpos120= yy->__thunkpos;  if (!yymatchString(yy, "")) goto l120;  goto l121;
  l120:;	  yy->__pos= yypos120; yy->__thunkpos= yythunkpos120;
  }
  l121:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pathempty", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_pathrootless(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathrootless"));  if (!yy_segmentnz(yy)) goto l122;
  l123:;	
  {  int yypos124= yy->__pos, yythunkpos124= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l124;  if (!yy_segment(yy)) goto l124;  goto l123;
  l124:;	  yy->__pos= yypos124; yy->__thunkpos= yythunkpos124;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathrootless", yy->__buf+yy->__pos));
  return 1;
  l122:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathrootless", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathabsolute(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathabsolute"));  if (!yymatchChar(yy, '/')) goto l125;
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_segmentnz(yy)) goto l126;
  l128:;	
  {  int yypos129= yy->__pos, yythunkpos129= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l129;  if (!yy_segment(yy)) goto l129;  goto l128;
  l129:;	  yy->__pos= yypos129; yy->__thunkpos= yythunkpos129;
  }  goto l127;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }
  l127:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pathabsolute", yy->__buf+yy->__pos));
  return 1;
  l125:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathabsolute", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathabempty(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "pathabempty"));
  l131:;	
  {  int yypos132= yy->__pos, yythunkpos132= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l132;  if (!yy_segment(yy)) goto l132;  goto l131;
  l132:;	  yy->__pos= yypos132; yy->__thunkpos= yythunkpos132;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathabempty", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_authority(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "authority"));
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;  if (!yy_userinfo(yy)) goto l134;  yyDo(yy, yySet, -3, 0);  if (!yymatchChar(yy, '@')) goto l134;  goto l135;
  l134:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;
  }
  l135:;	  if (!yy_host(yy)) goto l133;  yyDo(yy, yySet, -2, 0);
  {  int yypos136= yy->__pos, yythunkpos136= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l136;  if (!yy_port(yy)) goto l136;  yyDo(yy, yySet, -1, 0);  goto l137;
  l136:;	  yy->__pos= yypos136; yy->__thunkpos= yythunkpos136;
  }
  l137:;	  yyDo(yy, yy_1_authority, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "authority", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "authority", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l138;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alpha(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l139;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 1;
  l139:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yymatchDot(yy)) goto l141;  goto l140;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l140:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_fragment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "fragment"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l142;
#undef yytext
#undef yyleng
  }
  {  int yypos145= yy->__pos, yythunkpos145= yy->__thunkpos;  if (!yy_pchar(yy)) goto l146;  goto l145;
  l146:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yymatchChar(yy, '/')) goto l147;  goto l145;
  l147:;	  yy->__pos= yypos145; yy->__thunkpos= yythunkpos145;  if (!yymatchChar(yy, '?')) goto l142;
  }
  l145:;	
  l143:;	
  {  int yypos144= yy->__pos, yythunkpos144= yy->__thunkpos;
  {  int yypos148= yy->__pos, yythunkpos148= yy->__thunkpos;  if (!yy_pchar(yy)) goto l149;  goto l148;
  l149:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;  if (!yymatchChar(yy, '/')) goto l150;  goto l148;
  l150:;	  yy->__pos= yypos148; yy->__thunkpos= yythunkpos148;  if (!yymatchChar(yy, '?')) goto l144;
  }
  l148:;	  goto l143;
  l144:;	  yy->__pos= yypos144; yy->__thunkpos= yythunkpos144;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l142;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_fragment, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "fragment", yy->__buf+yy->__pos));
  return 1;
  l142:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "fragment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_query(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "query"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l151;
#undef yytext
#undef yyleng
  }
  {  int yypos154= yy->__pos, yythunkpos154= yy->__thunkpos;  if (!yy_pchar(yy)) goto l155;  goto l154;
  l155:;	  yy->__pos= yypos154; yy->__thunkpos= yythunkpos154;  if (!yymatchChar(yy, '/')) goto l156;  goto l154;
  l156:;	  yy->__pos= yypos154; yy->__thunkpos= yythunkpos154;  if (!yymatchChar(yy, '?')) goto l151;
  }
  l154:;	
  l152:;	
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_pchar(yy)) goto l158;  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yymatchChar(yy, '/')) goto l159;  goto l157;
  l159:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yymatchChar(yy, '?')) goto l153;
  }
  l157:;	  goto l152;
  l153:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l151;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_query, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "query", yy->__buf+yy->__pos));
  return 1;
  l151:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "query", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hierpart(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "hierpart"));
  {  int yypos161= yy->__pos, yythunkpos161= yy->__thunkpos;  if (!yymatchString(yy, "//")) goto l162;  if (!yy_authority(yy)) goto l162;  yyDo(yy, yySet, -1, 0);  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l162;
#undef yytext
#undef yyleng
  }  if (!yy_pathabempty(yy)) goto l162;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l162;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_hierpart, yy->__begin, yy->__end);  goto l161;
  l162:;	  yy->__pos= yypos161; yy->__thunkpos= yythunkpos161;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l160;
#undef yytext
#undef yyleng
  }
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy_pathabsolute(yy)) goto l164;  goto l163;
  l164:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;  if (!yy_pathrootless(yy)) goto l165;  goto l163;
  l165:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;  if (!yy_pathempty(yy)) goto l160;
  }
  l163:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l160;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_hierpart, yy->__begin, yy->__end);
  }
  l161:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "hierpart", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l160:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hierpart", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Scheme(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Scheme"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l166;
#undef yytext
#undef yyleng
  }  if (!yy_alpha(yy)) goto l166;
  l167:;	
  {  int yypos168= yy->__pos, yythunkpos168= yy->__thunkpos;
  {  int yypos169= yy->__pos, yythunkpos169= yy->__thunkpos;  if (!yy_alpha(yy)) goto l170;  goto l169;
  l170:;	  yy->__pos= yypos169; yy->__thunkpos= yythunkpos169;  if (!yy_digit(yy)) goto l171;  goto l169;
  l171:;	  yy->__pos= yypos169; yy->__thunkpos= yythunkpos169;  if (!yymatchChar(yy, '+')) goto l172;  goto l169;
  l172:;	  yy->__pos= yypos169; yy->__thunkpos= yythunkpos169;  if (!yymatchChar(yy, '-')) goto l173;  goto l169;
  l173:;	  yy->__pos= yypos169; yy->__thunkpos= yythunkpos169;  if (!yymatchChar(yy, '.')) goto l168;
  }
  l169:;	  goto l167;
  l168:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l166;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Scheme, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Scheme", yy->__buf+yy->__pos));
  return 1;
  l166:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Scheme", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 4, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos175= yy->__pos, yythunkpos175= yy->__thunkpos;  if (!yy_Scheme(yy)) goto l175;  yyDo(yy, yySet, -4, 0);  if (!yymatchChar(yy, ':')) goto l175;  goto l176;
  l175:;	  yy->__pos= yypos175; yy->__thunkpos= yythunkpos175;
  }
  l176:;	  if (!yy_hierpart(yy)) goto l174;  yyDo(yy, yySet, -3, 0);
  {  int yypos177= yy->__pos, yythunkpos177= yy->__thunkpos;  if (!yymatchChar(yy, '?')) goto l177;  if (!yy_query(yy)) goto l177;  yyDo(yy, yySet, -2, 0);  goto l178;
  l177:;	  yy->__pos= yypos177; yy->__thunkpos= yythunkpos177;
  }
  l178:;	
  {  int yypos179= yy->__pos, yythunkpos179= yy->__thunkpos;  if (!yymatchChar(yy, '#')) goto l179;  if (!yy_fragment(yy)) goto l179;  yyDo(yy, yySet, -1, 0);  goto l180;
  l179:;	  yy->__pos= yypos179; yy->__thunkpos= yythunkpos179;
  }
  l180:;	  if (!yy_EOF(yy)) goto l174;  yyDo(yy, yy_1_start, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 4, 0);
  return 1;
  l174:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 109 "/Users/rasmus/Development/C/uri/src/uri.leg"

