/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 37
#line 1 "/Users/rasmus/Development/C/uri/src/uri.leg"

#include "uri/element.h"
#include <stdio.h>

#define YYSTYPE element *
#ifdef __DEBUG__
#define YY_DEBUG 1
#endif

#define YY_INPUT(buf, result, max_size)                                        \
  {                                                                            \
    int yyc;                                                                   \
    if (charbuf && *charbuf != '\0') {                                         \
      yyc = *charbuf++;                                                        \
    } else {                                                                   \
      yyc = EOF;                                                               \
    }                                                                          \
    result = (EOF == yyc) ? 0 : (*(buf) = yyc, 1);                             \
  }

#define YY_RULE(T) T


#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_alpha2(yycontext *yy); /* 37 */
YY_RULE(int) yy_gendelims(yycontext *yy); /* 36 */
YY_RULE(int) yy_reserved(yycontext *yy); /* 35 */
YY_RULE(int) yy_decoctet(yycontext *yy); /* 34 */
YY_RULE(int) yy_ls32(yycontext *yy); /* 33 */
YY_RULE(int) yy_h16(yycontext *yy); /* 32 */
YY_RULE(int) yy_hexdigit(yycontext *yy); /* 31 */
YY_RULE(int) yy_IPvFuture(yycontext *yy); /* 30 */
YY_RULE(int) yy_IPv6address(yycontext *yy); /* 29 */
YY_RULE(int) yy_regname(yycontext *yy); /* 28 */
YY_RULE(int) yy_IPv4address(yycontext *yy); /* 27 */
YY_RULE(int) yy_IPliteral(yycontext *yy); /* 26 */
YY_RULE(int) yy_port(yycontext *yy); /* 25 */
YY_RULE(int) yy_host(yycontext *yy); /* 24 */
YY_RULE(int) yy_userinfo(yycontext *yy); /* 23 */
YY_RULE(int) yy_subdelims(yycontext *yy); /* 22 */
YY_RULE(int) yy_pctencoded(yycontext *yy); /* 21 */
YY_RULE(int) yy_unreserved(yycontext *yy); /* 20 */
YY_RULE(int) yy_pchar(yycontext *yy); /* 19 */
YY_RULE(int) yy_segmentnznc(yycontext *yy); /* 18 */
YY_RULE(int) yy_segmentnz(yycontext *yy); /* 17 */
YY_RULE(int) yy_segment(yycontext *yy); /* 16 */
YY_RULE(int) yy_pathnoscheme(yycontext *yy); /* 15 */
YY_RULE(int) yy_path(yycontext *yy); /* 14 */
YY_RULE(int) yy_pathempty(yycontext *yy); /* 13 */
YY_RULE(int) yy_pathrootless(yycontext *yy); /* 12 */
YY_RULE(int) yy_pathabsolute(yycontext *yy); /* 11 */
YY_RULE(int) yy_pathabempty(yycontext *yy); /* 10 */
YY_RULE(int) yy_authority(yycontext *yy); /* 9 */
YY_RULE(int) yy_digit(yycontext *yy); /* 8 */
YY_RULE(int) yy_alpha(yycontext *yy); /* 7 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 6 */
YY_RULE(int) yy_fragment(yycontext *yy); /* 5 */
YY_RULE(int) yy_query(yycontext *yy); /* 4 */
YY_RULE(int) yy_hierpart(yycontext *yy); /* 3 */
YY_RULE(int) yy_Scheme(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_hexdigit(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_hexdigit\n"));
  {
#line 106
  2;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_fragment(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_fragment\n"));
  {
#line 90
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_query(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_query\n"));
  {
#line 88
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_h16(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_h16\n"));
  {
#line 78
  4;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_IPv6address\n"));
  {
#line 70
  2;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_IPv6address\n"));
  {
#line 69
  3;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_IPv6address\n"));
  {
#line 68
  4;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_IPv6address\n"));
  {
#line 67
  5;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IPv6address(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IPv6address\n"));
  {
#line 66
  6;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_port(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_port\n"));
  {
#line 59
   __ = mk_integer(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_host(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_host\n"));
  {
#line 57
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_userinfo(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_userinfo\n"));
  {
#line 55
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_authority(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define h yy->__val[-2]
#define u yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_authority\n"));
  {
#line 53
   __ = mk_authority(u,h,p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef h
#undef u
}
YY_ACTION(void) yy_2_hierpart(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_hierpart\n"));
  {
#line 33
   __ = mk_hirhierarchical_part(mk_str(yytext), 0); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_hierpart(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_hierpart\n"));
  {
#line 32
   __ = mk_hirhierarchical_part(mk_str(yytext), a); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_Scheme(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Scheme\n"));
  {
#line 30
   __ = mk_str(yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_start(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define q yy->__val[-2]
#define h yy->__val[-3]
#define s yy->__val[-4]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_start\n"));
  {
#line 26
  
  parse_result = mk_uri(s, h, q, f);
;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef q
#undef h
#undef s
}

YY_RULE(int) yy_alpha2(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha2"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l1;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  l2:;	
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\100\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  l4:;	
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\100\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l1;
#undef yytext
#undef yyleng
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha2", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha2", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_gendelims(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "gendelims"));
  {  int yypos7= yy->__pos, yythunkpos7= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l8;  goto l7;
  l8:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '/')) goto l9;  goto l7;
  l9:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '?')) goto l10;  goto l7;
  l10:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '#')) goto l11;  goto l7;
  l11:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '[')) goto l12;  goto l7;
  l12:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, ']')) goto l13;  goto l7;
  l13:;	  yy->__pos= yypos7; yy->__thunkpos= yythunkpos7;  if (!yymatchChar(yy, '@')) goto l6;
  }
  l7:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "gendelims", yy->__buf+yy->__pos));
  return 1;
  l6:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "gendelims", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_reserved(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "reserved"));
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yy_gendelims(yy)) goto l16;  goto l15;
  l16:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;  if (!yy_subdelims(yy)) goto l14;
  }
  l15:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "reserved", yy->__buf+yy->__pos));
  return 1;
  l14:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "reserved", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_decoctet(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "decoctet"));
  l18:;	
  {  int yypos19= yy->__pos, yythunkpos19= yy->__thunkpos;  if (!yy_digit(yy)) goto l19;  goto l18;
  l19:;	  yy->__pos= yypos19; yy->__thunkpos= yythunkpos19;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "decoctet", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_ls32(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ls32"));
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yy_h16(yy)) goto l22;  if (!yymatchChar(yy, ':')) goto l22;  if (!yy_h16(yy)) goto l22;  goto l21;
  l22:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;  if (!yy_IPv4address(yy)) goto l20;
  }
  l21:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ls32", yy->__buf+yy->__pos));
  return 1;
  l20:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ls32", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_h16(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "h16"));  if (!yy_hexdigit(yy)) goto l23;  yyDo(yy, yy_1_h16, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "h16", yy->__buf+yy->__pos));
  return 1;
  l23:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "h16", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hexdigit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "hexdigit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l24;  yyDo(yy, yy_1_hexdigit, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hexdigit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPvFuture(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPvFuture"));  if (!yymatchChar(yy, 'v')) goto l25;  if (!yy_hexdigit(yy)) goto l25;  if (!yymatchChar(yy, '.')) goto l25;
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;
  {  int yypos28= yy->__pos, yythunkpos28= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l29;  goto l28;
  l29:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yy_subdelims(yy)) goto l30;  goto l28;
  l30:;	  yy->__pos= yypos28; yy->__thunkpos= yythunkpos28;  if (!yymatchChar(yy, ':')) goto l26;
  }
  l28:;	  goto l27;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }
  l27:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IPvFuture", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPvFuture", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPv6address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPv6address"));
  {  int yypos32= yy->__pos, yythunkpos32= yy->__thunkpos;  if (!yy_h16(yy)) goto l33;  if (!yymatchChar(yy, ':')) goto l33;  yyDo(yy, yy_1_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l33;  goto l32;
  l33:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchString(yy, "::")) goto l34;  if (!yy_h16(yy)) goto l34;  if (!yymatchChar(yy, ':')) goto l34;  yyDo(yy, yy_2_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l34;  goto l32;
  l34:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\000\102\000\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l35;  if (!yymatchString(yy, "::")) goto l35;  if (!yy_h16(yy)) goto l35;  if (!yymatchChar(yy, ':')) goto l35;  yyDo(yy, yy_3_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l35;  goto l32;
  l35:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\102\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l36;  if (!yymatchString(yy, "::")) goto l36;  if (!yy_h16(yy)) goto l36;  if (!yymatchChar(yy, ':')) goto l36;  yyDo(yy, yy_4_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l36;  goto l32;
  l36:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\106\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l37;  if (!yymatchString(yy, "::")) goto l37;  if (!yy_h16(yy)) goto l37;  if (!yymatchChar(yy, ':')) goto l37;  yyDo(yy, yy_5_IPv6address, yy->__begin, yy->__end);  if (!yy_ls32(yy)) goto l37;  goto l32;
  l37:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\112\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l38;  if (!yymatchString(yy, "::")) goto l38;  if (!yy_h16(yy)) goto l38;  if (!yymatchChar(yy, ':')) goto l38;  if (!yy_ls32(yy)) goto l38;  goto l32;
  l38:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\122\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l39;  if (!yymatchString(yy, "::")) goto l39;  if (!yy_ls32(yy)) goto l39;  goto l32;
  l39:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\142\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  if (!yymatchString(yy, "::")) goto l40;  if (!yy_h16(yy)) goto l40;  goto l32;
  l40:;	  yy->__pos= yypos32; yy->__thunkpos= yythunkpos32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\005\007\102\004\000\000\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l31;  if (!yymatchString(yy, "::")) goto l31;
  }
  l32:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IPv6address", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPv6address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_regname(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "regname"));
  {  int yypos44= yy->__pos, yythunkpos44= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l45;  goto l44;
  l45:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yy_pctencoded(yy)) goto l46;  goto l44;
  l46:;	  yy->__pos= yypos44; yy->__thunkpos= yythunkpos44;  if (!yy_subdelims(yy)) goto l41;
  }
  l44:;	
  l42:;	
  {  int yypos43= yy->__pos, yythunkpos43= yy->__thunkpos;
  {  int yypos47= yy->__pos, yythunkpos47= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l48;  goto l47;
  l48:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yy_pctencoded(yy)) goto l49;  goto l47;
  l49:;	  yy->__pos= yypos47; yy->__thunkpos= yythunkpos47;  if (!yy_subdelims(yy)) goto l43;
  }
  l47:;	  goto l42;
  l43:;	  yy->__pos= yypos43; yy->__thunkpos= yythunkpos43;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "regname", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "regname", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPv4address(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPv4address"));  if (!yy_decoctet(yy)) goto l50;  if (!yymatchChar(yy, '.')) goto l50;  if (!yy_decoctet(yy)) goto l50;  if (!yymatchChar(yy, '.')) goto l50;  if (!yy_decoctet(yy)) goto l50;  if (!yymatchChar(yy, '.')) goto l50;  if (!yy_decoctet(yy)) goto l50;
  yyprintf((stderr, "  ok   %s @ %s\n", "IPv4address", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPv4address", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IPliteral(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IPliteral"));  if (!yymatchChar(yy, '[')) goto l51;
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;  if (!yy_IPv6address(yy)) goto l53;  goto l52;
  l53:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  if (!yy_IPvFuture(yy)) goto l51;
  }
  l52:;	  if (!yymatchChar(yy, ']')) goto l51;
  yyprintf((stderr, "  ok   %s @ %s\n", "IPliteral", yy->__buf+yy->__pos));
  return 1;
  l51:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IPliteral", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_port(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "port"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l54;
#undef yytext
#undef yyleng
  }  if (!yy_digit(yy)) goto l54;
  l55:;	
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yy_digit(yy)) goto l56;  goto l55;
  l56:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l54;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_port, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 1;
  l54:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "port", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_host(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "host"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l57;
#undef yytext
#undef yyleng
  }
  {  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;  if (!yy_IPliteral(yy)) goto l59;  goto l58;
  l59:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;  if (!yy_IPv4address(yy)) goto l60;  goto l58;
  l60:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;  if (!yy_regname(yy)) goto l57;
  }
  l58:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l57;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_host, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "host", yy->__buf+yy->__pos));
  return 1;
  l57:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "host", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_userinfo(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "userinfo"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l61;
#undef yytext
#undef yyleng
  }
  {  int yypos64= yy->__pos, yythunkpos64= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l65;  goto l64;
  l65:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yy_pctencoded(yy)) goto l66;  goto l64;
  l66:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yy_subdelims(yy)) goto l67;  goto l64;
  l67:;	  yy->__pos= yypos64; yy->__thunkpos= yythunkpos64;  if (!yymatchChar(yy, ':')) goto l61;
  }
  l64:;	
  l62:;	
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yy_pctencoded(yy)) goto l70;  goto l68;
  l70:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yy_subdelims(yy)) goto l71;  goto l68;
  l71:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchChar(yy, ':')) goto l63;
  }
  l68:;	  goto l62;
  l63:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l61;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_userinfo, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "userinfo", yy->__buf+yy->__pos));
  return 1;
  l61:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "userinfo", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_subdelims(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "subdelims"));
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yymatchChar(yy, '!')) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '$')) goto l75;  goto l73;
  l75:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '&')) goto l76;  goto l73;
  l76:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '\'')) goto l77;  goto l73;
  l77:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '(')) goto l78;  goto l73;
  l78:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, ')')) goto l79;  goto l73;
  l79:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '*')) goto l80;  goto l73;
  l80:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '+')) goto l81;  goto l73;
  l81:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, ',')) goto l82;  goto l73;
  l82:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, ';')) goto l83;  goto l73;
  l83:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchChar(yy, '=')) goto l72;
  }
  l73:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "subdelims", yy->__buf+yy->__pos));
  return 1;
  l72:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "subdelims", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pctencoded(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pctencoded"));  if (!yymatchChar(yy, '%')) goto l84;  if (!yy_hexdigit(yy)) goto l84;
  yyprintf((stderr, "  ok   %s @ %s\n", "pctencoded", yy->__buf+yy->__pos));
  return 1;
  l84:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pctencoded", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_unreserved(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "unreserved"));
  {  int yypos86= yy->__pos, yythunkpos86= yy->__thunkpos;  if (!yy_alpha(yy)) goto l87;  goto l86;
  l87:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;  if (!yy_digit(yy)) goto l88;  goto l86;
  l88:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;  if (!yymatchChar(yy, '-')) goto l89;  goto l86;
  l89:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;  if (!yymatchChar(yy, '.')) goto l90;  goto l86;
  l90:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;  if (!yymatchChar(yy, '_')) goto l91;  goto l86;
  l91:;	  yy->__pos= yypos86; yy->__thunkpos= yythunkpos86;  if (!yymatchChar(yy, '~')) goto l85;
  }
  l86:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "unreserved", yy->__buf+yy->__pos));
  return 1;
  l85:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "unreserved", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pchar(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pchar"));
  {  int yypos93= yy->__pos, yythunkpos93= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l94;  goto l93;
  l94:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;  if (!yy_pctencoded(yy)) goto l95;  goto l93;
  l95:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;  if (!yy_subdelims(yy)) goto l96;  goto l93;
  l96:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;  if (!yymatchChar(yy, ':')) goto l97;  goto l93;
  l97:;	  yy->__pos= yypos93; yy->__thunkpos= yythunkpos93;  if (!yymatchChar(yy, '@')) goto l92;
  }
  l93:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pchar", yy->__buf+yy->__pos));
  return 1;
  l92:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pchar", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segmentnznc(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "segmentnznc"));
  {  int yypos101= yy->__pos, yythunkpos101= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l102;  goto l101;
  l102:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;  if (!yy_pctencoded(yy)) goto l103;  goto l101;
  l103:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;  if (!yy_subdelims(yy)) goto l104;  goto l101;
  l104:;	  yy->__pos= yypos101; yy->__thunkpos= yythunkpos101;  if (!yymatchChar(yy, '@')) goto l98;
  }
  l101:;	
  l99:;	
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yy_unreserved(yy)) goto l106;  goto l105;
  l106:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_pctencoded(yy)) goto l107;  goto l105;
  l107:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yy_subdelims(yy)) goto l108;  goto l105;
  l108:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;  if (!yymatchChar(yy, '@')) goto l100;
  }
  l105:;	  goto l99;
  l100:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segmentnznc", yy->__buf+yy->__pos));
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "segmentnznc", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segmentnz(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "segmentnz"));  if (!yy_pchar(yy)) goto l109;
  l110:;	
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;  if (!yy_pchar(yy)) goto l111;  goto l110;
  l111:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segmentnz", yy->__buf+yy->__pos));
  return 1;
  l109:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "segmentnz", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_segment(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "segment"));
  l113:;	
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yy_pchar(yy)) goto l114;  goto l113;
  l114:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "segment", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_pathnoscheme(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathnoscheme"));  if (!yy_segmentnznc(yy)) goto l115;
  l116:;	
  {  int yypos117= yy->__pos, yythunkpos117= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l117;  if (!yy_segment(yy)) goto l117;  goto l116;
  l117:;	  yy->__pos= yypos117; yy->__thunkpos= yythunkpos117;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathnoscheme", yy->__buf+yy->__pos));
  return 1;
  l115:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathnoscheme", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_path(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "path"));
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yy_pathabempty(yy)) goto l120;  goto l119;
  l120:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_pathabsolute(yy)) goto l121;  goto l119;
  l121:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_pathnoscheme(yy)) goto l122;  goto l119;
  l122:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_pathrootless(yy)) goto l123;  goto l119;
  l123:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_pathempty(yy)) goto l118;
  }
  l119:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "path", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "path", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathempty(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "pathempty"));
  {  int yypos125= yy->__pos, yythunkpos125= yy->__thunkpos;  if (!yymatchString(yy, "")) goto l125;  goto l126;
  l125:;	  yy->__pos= yypos125; yy->__thunkpos= yythunkpos125;
  }
  l126:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pathempty", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_pathrootless(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathrootless"));  if (!yy_segmentnz(yy)) goto l127;
  l128:;	
  {  int yypos129= yy->__pos, yythunkpos129= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l129;  if (!yy_segment(yy)) goto l129;  goto l128;
  l129:;	  yy->__pos= yypos129; yy->__thunkpos= yythunkpos129;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathrootless", yy->__buf+yy->__pos));
  return 1;
  l127:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathrootless", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathabsolute(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pathabsolute"));  if (!yymatchChar(yy, '/')) goto l130;
  {  int yypos131= yy->__pos, yythunkpos131= yy->__thunkpos;  if (!yy_segmentnz(yy)) goto l131;
  l133:;	
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l134;  if (!yy_segment(yy)) goto l134;  goto l133;
  l134:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;
  }  goto l132;
  l131:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;
  }
  l132:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "pathabsolute", yy->__buf+yy->__pos));
  return 1;
  l130:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pathabsolute", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pathabempty(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "pathabempty"));
  l136:;	
  {  int yypos137= yy->__pos, yythunkpos137= yy->__thunkpos;  if (!yymatchChar(yy, '/')) goto l137;  if (!yy_segment(yy)) goto l137;  goto l136;
  l137:;	  yy->__pos= yypos137; yy->__thunkpos= yythunkpos137;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "pathabempty", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_authority(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "authority"));
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yy_userinfo(yy)) goto l139;  yyDo(yy, yySet, -3, 0);  if (!yymatchChar(yy, '@')) goto l139;  goto l140;
  l139:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;
  }
  l140:;	  if (!yy_host(yy)) goto l138;  yyDo(yy, yySet, -2, 0);
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yymatchChar(yy, ':')) goto l141;  if (!yy_port(yy)) goto l141;  yyDo(yy, yySet, -1, 0);  goto l142;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }
  l142:;	  yyDo(yy, yy_1_authority, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "authority", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "authority", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l143;
  yyprintf((stderr, "  ok   %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 1;
  l143:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_alpha(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "alpha"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l144;
  yyprintf((stderr, "  ok   %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 1;
  l144:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "alpha", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos146= yy->__pos, yythunkpos146= yy->__thunkpos;  if (!yymatchDot(yy)) goto l146;  goto l145;
  l146:;	  yy->__pos= yypos146; yy->__thunkpos= yythunkpos146;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l145:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_fragment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "fragment"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l147;
#undef yytext
#undef yyleng
  }
  {  int yypos150= yy->__pos, yythunkpos150= yy->__thunkpos;  if (!yy_pchar(yy)) goto l151;  goto l150;
  l151:;	  yy->__pos= yypos150; yy->__thunkpos= yythunkpos150;  if (!yymatchChar(yy, '/')) goto l152;  goto l150;
  l152:;	  yy->__pos= yypos150; yy->__thunkpos= yythunkpos150;  if (!yymatchChar(yy, '?')) goto l147;
  }
  l150:;	
  l148:;	
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;
  {  int yypos153= yy->__pos, yythunkpos153= yy->__thunkpos;  if (!yy_pchar(yy)) goto l154;  goto l153;
  l154:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;  if (!yymatchChar(yy, '/')) goto l155;  goto l153;
  l155:;	  yy->__pos= yypos153; yy->__thunkpos= yythunkpos153;  if (!yymatchChar(yy, '?')) goto l149;
  }
  l153:;	  goto l148;
  l149:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l147;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_fragment, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "fragment", yy->__buf+yy->__pos));
  return 1;
  l147:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "fragment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_query(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "query"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l156;
#undef yytext
#undef yyleng
  }
  {  int yypos159= yy->__pos, yythunkpos159= yy->__thunkpos;  if (!yy_pchar(yy)) goto l160;  goto l159;
  l160:;	  yy->__pos= yypos159; yy->__thunkpos= yythunkpos159;  if (!yymatchChar(yy, '/')) goto l161;  goto l159;
  l161:;	  yy->__pos= yypos159; yy->__thunkpos= yythunkpos159;  if (!yymatchChar(yy, '?')) goto l156;
  }
  l159:;	
  l157:;	
  {  int yypos158= yy->__pos, yythunkpos158= yy->__thunkpos;
  {  int yypos162= yy->__pos, yythunkpos162= yy->__thunkpos;  if (!yy_pchar(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;  if (!yymatchChar(yy, '/')) goto l164;  goto l162;
  l164:;	  yy->__pos= yypos162; yy->__thunkpos= yythunkpos162;  if (!yymatchChar(yy, '?')) goto l158;
  }
  l162:;	  goto l157;
  l158:;	  yy->__pos= yypos158; yy->__thunkpos= yythunkpos158;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l156;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_query, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "query", yy->__buf+yy->__pos));
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "query", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_hierpart(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "hierpart"));
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yymatchString(yy, "//")) goto l167;  if (!yy_authority(yy)) goto l167;  yyDo(yy, yySet, -1, 0);  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l167;
#undef yytext
#undef yyleng
  }  if (!yy_pathabempty(yy)) goto l167;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l167;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_hierpart, yy->__begin, yy->__end);  goto l166;
  l167:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l165;
#undef yytext
#undef yyleng
  }
  {  int yypos168= yy->__pos, yythunkpos168= yy->__thunkpos;  if (!yy_pathabsolute(yy)) goto l169;  goto l168;
  l169:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;  if (!yy_pathrootless(yy)) goto l170;  goto l168;
  l170:;	  yy->__pos= yypos168; yy->__thunkpos= yythunkpos168;  if (!yy_pathempty(yy)) goto l165;
  }
  l168:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l165;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_hierpart, yy->__begin, yy->__end);
  }
  l166:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "hierpart", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l165:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "hierpart", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Scheme(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Scheme"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l171;
#undef yytext
#undef yyleng
  }  if (!yy_alpha(yy)) goto l171;
  l172:;	
  {  int yypos173= yy->__pos, yythunkpos173= yy->__thunkpos;
  {  int yypos174= yy->__pos, yythunkpos174= yy->__thunkpos;  if (!yy_alpha(yy)) goto l175;  goto l174;
  l175:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;  if (!yy_digit(yy)) goto l176;  goto l174;
  l176:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;  if (!yymatchChar(yy, '+')) goto l177;  goto l174;
  l177:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;  if (!yymatchChar(yy, '-')) goto l178;  goto l174;
  l178:;	  yy->__pos= yypos174; yy->__thunkpos= yythunkpos174;  if (!yymatchChar(yy, '.')) goto l173;
  }
  l174:;	  goto l172;
  l173:;	  yy->__pos= yypos173; yy->__thunkpos= yythunkpos173;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l171;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Scheme, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Scheme", yy->__buf+yy->__pos));
  return 1;
  l171:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Scheme", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 4, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos180= yy->__pos, yythunkpos180= yy->__thunkpos;  if (!yy_Scheme(yy)) goto l180;  yyDo(yy, yySet, -4, 0);  if (!yymatchChar(yy, ':')) goto l180;  goto l181;
  l180:;	  yy->__pos= yypos180; yy->__thunkpos= yythunkpos180;
  }
  l181:;	  if (!yy_hierpart(yy)) goto l179;  yyDo(yy, yySet, -3, 0);
  {  int yypos182= yy->__pos, yythunkpos182= yy->__thunkpos;  if (!yymatchChar(yy, '?')) goto l182;  if (!yy_query(yy)) goto l182;  yyDo(yy, yySet, -2, 0);  goto l183;
  l182:;	  yy->__pos= yypos182; yy->__thunkpos= yythunkpos182;
  }
  l183:;	
  {  int yypos184= yy->__pos, yythunkpos184= yy->__thunkpos;  if (!yymatchChar(yy, '#')) goto l184;  if (!yy_fragment(yy)) goto l184;  yyDo(yy, yySet, -1, 0);  goto l185;
  l184:;	  yy->__pos= yypos184; yy->__thunkpos= yythunkpos184;
  }
  l185:;	  if (!yy_EOF(yy)) goto l179;  yyDo(yy, yy_1_start, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 4, 0);
  return 1;
  l179:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 110 "/Users/rasmus/Development/C/uri/src/uri.leg"

